package za.co.ibear.code.gizmo.unit.swt;

import za.co.ibear.code.gizmo.GizmoUnitBrowse;

public class GizmoUnitBrowseDialog extends GizmoUnitBrowse {

	public GizmoUnitBrowseDialog() throws Exception {
		super("UnitBrowseDialog",GizmoUnitEditorConstant.PACKAGE_PREFIX,GizmoUnitEditorConstant.PATH_PREFIX);

		content = content + "import java.beans.PropertyChangeEvent;\n";
		content = content + "import java.beans.PropertyChangeListener;\n";
		content = content + "import java.beans.PropertyChangeSupport;\n";
		content = content + "import java.lang.reflect.Constructor;\n";
		content = content + "import java.util.ArrayList;\n";
		content = content + "import java.util.HashMap;\n";
		content = content + "import java.util.List;\n";
		content = content + "import java.util.Map;\n";
		content = content + "import java.util.TreeSet;\n";
		content = content + "import org.eclipse.jface.dialogs.Dialog;\n";
		content = content + "import org.eclipse.swt.SWT;\n";
		content = content + "import org.eclipse.swt.events.DisposeEvent;\n";
		content = content + "import org.eclipse.swt.events.DisposeListener;\n";
		content = content + "import org.eclipse.swt.graphics.Point;\n";
		content = content + "import org.eclipse.swt.graphics.Rectangle;\n";
		content = content + "import org.eclipse.swt.widgets.Composite;\n";
		content = content + "import org.eclipse.swt.widgets.Control;\n";
		content = content + "import org.eclipse.swt.widgets.Shell;\n";
		content = content + "import org.eclipse.swt.layout.FillLayout;\n";
		content = content + "import za.co.ibear.code.gizmo.unit.swt.GizmoUnitEditorConstant;\n";
		content = content + "public class UnitBrowseDialog extends Dialog {\n";
		content = content + "	private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);\n";
		content = content + "	private Composite container;\n";
		content = content + "	private int width = 777;\n";
		content = content + "	private Composite relativeParent;\n";
		content = content + "	private String unitName;\n";
		content = content + "	private UnitBrowseDialogState state = new UnitBrowseDialogState();\n";
		content = content + "	public void setState(UnitBrowseDialogState state) {\n";
		content = content + "		this.state = state;\n";
		content = content + "	}\n";
		content = content + "	private Map<String,UnitBrowseDialogState> unitBorwseStateMap = new HashMap<String,UnitBrowseDialogState>();\n";
		content = content + "	private boolean SINGLE_SELECT = false;\n";
		content = content + "	\n";
		content = content + "	private List<String> initFilter = new ArrayList<String>();\n";
		content = content + "	\n";
		content = content + "	private Map<String,TreeSet<String>> selection = new HashMap<String,TreeSet<String>>();\n";
		content = content + "	\n";
		content = content + "	public UnitBrowseDialog(Shell parentShell,int width,Composite relativeParent,String unitName,boolean SINGLE_SELECT,List<String> initFilter) {\n";
		content = content + "		super(parentShell);\n";
		content = content + "		this.width = width;\n";
		content = content + "		this.relativeParent = relativeParent;\n";
		content = content + "		this.setUnitName(unitName);\n";
		content = content + "		this.setInitFilter(initFilter);\n";
		content = content + "		this.SINGLE_SELECT = SINGLE_SELECT;\n";
		content = content + "	}\n";
		content = content + "	@SuppressWarnings({ rawtypes, unchecked })\n";
		content = content + "	@Override\n";
		content = content + "	protected Control createDialogArea(Composite parent) {\n";
		content = content + "		container = (Composite) super.createDialogArea(parent);\n";
		content = content + "		container.setLayout(new FillLayout(SWT.HORIZONTAL));\n";
		content = content + "		parent.getShell().setText(Select);\n";
		content = content + "		try {\n";
		content = content + "			String name = GizmoUnitEditorConstant.PACKAGE_PREFIX + unitName.toLowerCase() + . + unitName + Browser;\n";
		content = content + "			Class dialog = Class.forName(name);\n";
		content = content + "			Constructor constructor = dialog.getConstructor(Composite.class,int.class,UnitBrowseDialogState.class,Map.class,boolean.class,List.class,Map.class);\n";
		content = content + "			UnitBrowseComposite browser = (UnitBrowseComposite) constructor.newInstance(container,SWT.NONE,state,unitBorwseStateMap,this.SINGLE_SELECT,this.getInitFilter(),this.selection);\n";
		content = content + "			browser.addDisposeListener(new DisposeListener() {\n";
		content = content + "				public void widgetDisposed(DisposeEvent e) {\n";
		content = content + "					firePropertyChange(select,null,state);\n";
		content = content + "				}\n";
		content = content + "			});\n";
		content = content + "			browser.addPropertyChangeListener(selection_changed,new PropertyChangeListener() {\n";
		content = content + "				public void propertyChange(final PropertyChangeEvent e) {\n";
		content = content + "					firePropertyChange(selection_changed,null,e.getNewValue());\n";
		content = content + "				}\n";
		content = content + "			});\n";
		content = content + "			browser.addPropertyChangeListener(save_unit_browse_state,new PropertyChangeListener() {\n";
		content = content + "				public void propertyChange(final PropertyChangeEvent e) {\n";
		content = content + "					unitBorwseStateMap = null;\n";
		content = content + "					unitBorwseStateMap = (Map<String,UnitBrowseDialogState>) e.getNewValue();\n";
		content = content + "				}\n";
		content = content + "			});\n";
		content = content + "			browser.addPropertyChangeListener(save_state,new PropertyChangeListener() {\n";
		content = content + "				public void propertyChange(final PropertyChangeEvent e) {\n";
		content = content + "					saveState((UnitBrowseDialogState) e.getNewValue());\n";
		content = content + "				}\n";
		content = content + "			});\n";
		content = content + "			browser.addPropertyChangeListener(close,new PropertyChangeListener() {\n";
		content = content + "				public void propertyChange(final PropertyChangeEvent e) {\n";
		content = content + "					close();\n";
		content = content + "				}\n";
		content = content + "			});\n";
		content = content + "		} catch (Exception e) {\n";
		content = content + "			e.printStackTrace();\n";
		content = content + "		}\n";
		content = content + "		getShell().setSize(width,470);\n";
		content = content + "		setDialogLocation();\n";
		content = content + "		return container;\n";
		content = content + "	}\n";
		content = content + "	public void saveState(UnitBrowseDialogState stateToSave) {\n";
		content = content + "		state = null;\n";
		content = content + "		state = stateToSave;\n";
		content = content + "		state.setUnitName(unitName);\n";
		content = content + "	}\n";
		content = content + "	public UnitBrowseDialogState getState() {\n";
		content = content + "		return state;\n";
		content = content + "	}\n";
		content = content + "	\n";
		content = content + "	private void setDialogLocation() {\n";
		content = content + "		getShell().setLocation(relativeParent.toDisplay(new Point(0,0)));\n";
		content = content + "		Rectangle dialog = getShell().getBounds();\n";
		content = content + "		Rectangle display = getShell().getDisplay().getBounds();\n";
		content = content + "		int y_adjust = display.height - (dialog.y + dialog.height);\n";
		content = content + "		int x_ajust = display.width - (dialog.x + dialog.width);\n";
		content = content + "		int x = dialog.x;\n";
		content = content + "		int y = dialog.y;\n";
		content = content + "		if(y_adjust<0) {\n";
		content = content + "			y = (y + y_adjust)-20;\n";
		content = content + "		}\n";
		content = content + "		if(x_ajust<0) {\n";
		content = content + "			x = (x + x_ajust)-20;\n";
		content = content + "		}\n";
		content = content + "		getShell().setLocation(x,y);\n";
		content = content + "	}\n";
		content = content + "	protected void setShellStyle(int arg0) {\n";
		content = content + "		super.setShellStyle(SWT.APPLICATION_MODAL | SWT.TOOL |  SWT.CLOSE | SWT.RESIZE);\n";
		content = content + "	}\n";
		content = content + "	@Override\n";
		content = content + "	protected void createButtonsForButtonBar(Composite parent) {\n";
		content = content + "	}\n";
		content = content + "	public void addPropertyChangeListener(PropertyChangeListener listener) {\n";
		content = content + "		changeSupport.addPropertyChangeListener(listener);\n";
		content = content + "	}\n";
		content = content + "	public void removePropertyChangeListener(PropertyChangeListener listener) {\n";
		content = content + "		changeSupport.removePropertyChangeListener(listener);\n";
		content = content + "	}\n";
		content = content + "	public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {\n";
		content = content + "		changeSupport.addPropertyChangeListener(propertyName, listener);\n";
		content = content + "	}\n";
		content = content + "	public void removePropertyChangeListener(String propertyName, PropertyChangeListener listener) {\n";
		content = content + "		changeSupport.removePropertyChangeListener(propertyName, listener);\n";
		content = content + "	}\n";
		content = content + "	protected void firePropertyChange(String propertyName, Object oldValue,	Object newValue) {\n";
		content = content + "		changeSupport.firePropertyChange(propertyName, oldValue, newValue);\n";
		content = content + "	}\n";
		content = content + "	protected void firePropertyChange(String propertyName, Object value) {\n";
		content = content + "		changeSupport.firePropertyChange(propertyName, value, null);\n";
		content = content + "	}\n";
		content = content + "	@Override\n";
		content = content + "	protected Point getInitialSize() {\n";
		content = content + "		return new Point(450, 300);\n";
		content = content + "	}\n";
		content = content + "	public String getUnitName() {\n";
		content = content + "		return unitName;\n";
		content = content + "	}\n";
		content = content + "	public void setUnitName(String unitName) {\n";
		content = content + "		this.unitName = unitName;\n";
		content = content + "	}\n";
		content = content + "	public Map<String,UnitBrowseDialogState> getUnitBorwseStateMap() {\n";
		content = content + "		return unitBorwseStateMap;\n";
		content = content + "	}\n";
		content = content + "	public void setUnitBorwseStateMap(Map<String,UnitBrowseDialogState> unitBorwseStateMap) {\n";
		content = content + "		this.unitBorwseStateMap = unitBorwseStateMap;\n";
		content = content + "	}\n";
		content = content + "	public List<String> getInitFilter() {\n";
		content = content + "		return initFilter;\n";
		content = content + "	}\n";
		content = content + "	public void setInitFilter(List<String> initFilter) {\n";
		content = content + "		this.initFilter = initFilter;\n";
		content = content + "	}\n";
		content = content + "	public Map<String, TreeSet<String>> getSelection() {\n";
		content = content + "		return selection;\n";
		content = content + "	}\n";
		content = content + "	public void setSelection(Map<String, TreeSet<String>> selection) {\n";
		content = content + "		this.selection = selection;\n";
		content = content + "	}\n";
		content = content + "	protected void p(String v) {\n";
		content = content + "		System.out.println(this.getClass().getName() + :) + v);\n";
		content = content + "	}\n";
		content = content + "}\n";

		createFile();		
	}
	
	@Override
	protected void p(String v) {
		System.out.println(this.getClass().getSimpleName() + ":) " + v);
	}

}
